# Generated by Django 4.2.1 on 2023-06-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="staff",
            fields=[
                ("s_id", models.AutoField(primary_key=True, serialize=False)),
                ("s_name", models.CharField(blank=True, max_length=255, null=True)),
                ("s_surname", models.CharField(blank=True, max_length=255, null=True)),
                ("s_age", models.IntegerField(blank=True, null=True)),
                ("s_contact", models.IntegerField(blank=True, null=True)),
                ("s_address", models.TextField(blank=True, null=True)),
                ("s_profile", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "s_gender",
                    models.CharField(
                        choices=[
                            ("female", "female"),
                            ("male", "male"),
                            ("other", "other"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
