# Generated by Django 4.2.1 on 2023-06-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_staff_s_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="s_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
